include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - avoid_unnecessary_containers
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_this
    - avoid_redundant_argument_values
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - use_rethrow_when_possible
    - unnecessary_null_in_if_null_operators

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
